### ISSUE TITLE
Preview - Text Imported from Google Docs Display Error (Workarounds Included)

### ISSUE THREAD

**Issue by Neo9421** [dons20/steam-review-editor#13]
Hey! Thanks for making this tool!
I'd just like to report an issue I've been having with it.

Text Copied and Pasted from Google Documents will have the text shown on the review writing field and review preview display appear with chosen coloured text in Google Docs.

Example with black coloured text (default to Google Docs):
<img width="908" alt="Screenshot_61" src="https://github.com/dons20/steam-review-editor/assets/164219967/75787e4b-e0cf-4a73-be2a-97780d610590">
<img width="915" alt="Screenshot_62" src="https://github.com/dons20/steam-review-editor/assets/164219967/8b73f849-ddca-4d99-8bd2-89760b96c2f1">

Example with white-coloured text (attempt to solve the issue):
<img width="908" alt="Screenshot_63" src="https://github.com/dons20/steam-review-editor/assets/164219967/88b79f5b-56cb-411f-b919-e9afd09fc0b1">
(Don't mind the red underlines, Grammarly put them there because I put goofy text)
<img width="915" alt="Screenshot_64" src="https://github.com/dons20/steam-review-editor/assets/164219967/f78a631c-23ab-4756-9003-c20dfa4a83b3">

Though the white text does solve the issue for the preview, it also makes it very difficult to use the edit field for formatting purposes.

But I think I might have found a workaround. By using a shade of grey, the text is somewhat visible in the typing field and has better visibility in the preview field. (Examples below)

<img width="908" alt="Screenshot_65" src="https://github.com/dons20/steam-review-editor/assets/164219967/ca76f233-e009-4b3b-b78d-49f6ef22bd27">
<img width="915" alt="Screenshot_66" src="https://github.com/dons20/steam-review-editor/assets/164219967/05ab5c47-8f9b-4d9f-9f98-393ee948b8bf">

I'm also quite sure why the markdown preview tab puts a `[/spoiler]` at the end of every line, but I think this might not affect the result.
(I tried pasting centre-aligned text and left-aligned text to see if it would make a difference, but the `[/spoiler]` markdown still shows up, I'm not quite sure what causes it, might be related to Google Docs itself)

I'd like to thank you once again for making this tool! Cheers!

Edit: Just found out that copying the text and pasting it into Notepad seems to resolve both issues. Whoops... Sorry!

**Comment by dons20** [comment]
Hi, thanks for checking out the tool! This is something I'd like to resolve.

I've released some small updates within the past day, I'll try it out with copied text from Google Docs to see if it has been addressed in Quill (the editor)

**Comment by dons20** [comment]
I've resolved the weird spoiler tag being added at the end. I will be fixing this other issue soon also.
