### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by CaliberPlex** [dons20/steam-review-editor#4]
This might be client-side for me, _or better yet just me being stupid cuz I'm not too familiar with this site,_ but when trying to use the link to the website app (http://dons20.github.io/sre), it says the page doesn't exist or rather, _"There isn't a GitHub Pages site here."_ I ended up just installing the css zip file myself in which it worked fine then (looks great and performs _stupendously_ btw).

**Comment by dons20** [comment]
Hi, thanks for bringing my attention to that, I could've sworn I updated the link. 

Here is the new link (no longer using Github Pages): [Steam Review Editor v1](https://projects.claytoninnovations.com/steam-review-editor/)

Let me know if you have any issues accessing that one.

> (looks great and performs stupendously btw)

Thank you very much, glad you like it!

**Comment by CaliberPlex** [comment]
Wow that was fast! Thanks for the quick fix!
