### ISSUE TITLE
URL Broken

### ISSUE THREAD

**Issue by BadgerCode** [dons20/steam-review-editor#7]
Hey.

I just noticed the link in your [reddit posts](https://www.reddit.com/r/Steam/comments/5p7mqd/i_made_a_tool_for_writing_previewing_reviews/) no longer works

https://dons20.github.io/sre/

https://projects.claytoninnovations.com/steam-review-editor/ continues to work fine

**Comment by dons20** [comment]
Oh wow I didn't think anyone would still use those links, but I went ahead and updated it. It seems that automod had a problem with me updating it so long afterwards so it might take a while to show the new url.
